name: Android CI #可选-workflows名称。省略则将使用文件名
run-name: ${{github.actor}}Actions #可选-workflows运行名

# on: [push] #触发条件：定时 手动 push等
on:
  workflow_dispatch: 

jobs: #将workflows中运行的所有job分组在一起。
  build-job: #定义名为build-job 的job。子键将定义job的属性。
    runs-on: ubuntu-latest #作业在最新版本的Ubuntu Linux runner上运行。

    steps: #将build job中运行的所有步骤组合在一起
    
    - name: Check out repository #名称，可选项
      uses: actions/checkout@v3 #checkout代码到runner
      with:
        submodules: true
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3 #使用指定Java
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Build with Gradle
      # run: ./gradlew assembleDebug lintVitalRelease #runner上执行命令
      run: ./gradlew assembleRelease #release版本
    - name: Upload artifact
      uses: actions/upload-artifact@v3 #上传文件
      with:
        name: app-release.apk
        # path: app/build/outputs/apk/debug/app-debug.apk
        path: app/build/outputs/apk/release/app-release.apk
        retention-days: 30 #10天后文件过期
